language: haskell
ghc:
    - "8.4.1"
    - "8.2"
    - "8.0"
    - "7.10"
    - "7.8"

before_install:
    - cabal check
    - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh -O - --quiet | sh -s .
